[package]
# Semantic versioning: https://semver.org/
version = "0.9.2"

title = "Model Exploder"
description="Separate model parts to view their relationship and how they fit together."
authors = ["Syntway"]

category = "Tools"
keywords = ["kit", "tool", "tools", "util", "utils", "explode model", "exploded view"]

repository = "https://github.com/syntway/model_exploder"

icon = "data/icons/ext.png"
preview_image = "data/preview.png"

readme = "docs/README.md"
changelog = "docs/CHANGELOG.md"


[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.viewport.utility" = {}
"omni.ui.scene" = {}
"omni.usd" = {}


[[python.module]]
name = "syntway.model_exploder"
